var spotsData = [
  { id:"s-yeojwa", rid:"changwon", region:"창원·진해", title:"여좌천 로망스다리", cat:"대표", desc:"1.5km 벚꽃 터널. 드라마 같은 로맨틱 명소.", photo:"다리 중앙에서 양쪽 터널 구도. 야간 19~22시.", atmo:"로맨틱", crowd:"매우 혼잡", tr:{sub:"없음",bus:"315번 여좌동",car:"진해IC 10분",prk:"매우 어려움",day:"부산 1시간"}, tags:["로맨틱","야경","포토스팟"] },
  { id:"s-gyeonghwa", rid:"changwon", region:"창원·진해", title:"경화역", cat:"대표", desc:"벚꽃 터널 속 폐역. 선로 위 인생샷 명소.", photo:"선로 위 원근감 구도. 오전 9시 전.", atmo:"감성적", crowd:"매우 혼잡", tr:{sub:"없음",bus:"진해 시내버스",car:"진해IC 15분",prk:"어려움",day:"부산 1시간"}, tags:["폐역","인생샷","감성"] },
  { id:"s-yeouido", rid:"seoul", region:"서울", title:"여의도 윤중로", cat:"대표", desc:"서울 최고 벚꽃길. 1.7km 1,800그루 터널.", photo:"아침 7시 전 인파 없는 사진. 63빌딩 구도.", atmo:"도시적", crowd:"매우 혼잡", tr:{sub:"5호선 여의나루역 1번",bus:"여의도 다수",car:"축제기간 통제",prk:"불가",day:"서울 시내"}, tags:["도심","접근성","한강"] },
  { id:"s-seokchon", rid:"seoul", region:"서울", title:"석촌호수", cat:"대표", desc:"롯데타워+호수 반영. 도심 데이트 최고.", photo:"서호에서 타워+벚꽃 구도. 야간 추천.", atmo:"도시적", crowd:"혼잡", tr:{sub:"2·8호선 잠실역",bus:"잠실역 다수",car:"롯데월드몰 주차",prk:"유료",day:"서울 시내"}, tags:["호수","야경","데이트"] },
  { id:"s-namsan", rid:"seoul", region:"서울", title:"남산 둘레길", cat:"숨은", desc:"여의도보다 한적한 도심 벚꽃+시티뷰.", photo:"소월길 시티뷰+벚꽃. 케이블카 조망.", atmo:"산책", crowd:"보통", tr:{sub:"4호선 명동역→케이블카",bus:"남산순환 02,05",car:"남산터널",prk:"어려움",day:"서울 시내"}, tags:["한적","전망","산책"] },
  { id:"s-gyeongpo", rid:"gangneung", region:"강릉", title:"경포호·경포대", cat:"대표", desc:"4.3km 호수 둘레길. 고요한 반영 절경.", photo:"바람 없는 아침 호수 반영. 경포대 전경.", atmo:"자연적", crowd:"보통", tr:{sub:"없음 (KTX 강릉역)",bus:"202번",car:"강릉IC 20분",prk:"보통",day:"서울 KTX 2시간"}, tags:["호수","반영","자연"] },
  { id:"s-nokchanro", rid:"seogwipo", region:"서귀포·제주", title:"녹산로 꽃길", cat:"숨은", desc:"유채꽃+벚꽃 동시 개화. 제주만의 컬러풀 꽃길.", photo:"양쪽 꽃길 구도. 맑은 날 한라산 배경.", atmo:"동화적", crowd:"한적", tr:{sub:"없음",bus:"배차 김",car:"렌터카 추천",prk:"도로변",day:"제주 30분"}, tags:["유채꽃","드라이브","한라산"] },
  { id:"s-eworld", rid:"daegu", region:"대구", title:"이월드 & 83타워", cat:"대표", desc:"83타워 야경+LED 벚꽃 조명. 밤벚꽃 진수.", photo:"타워 전망대 파노라마. 야간 LED 포토존.", atmo:"화려한", crowd:"혼잡", tr:{sub:"2호선 두류역",bus:"이월드 방면",car:"달서IC 10분",prk:"이월드 주차장",day:"KTX 동대구 1.5시간"}, tags:["야경","놀이공원","타워"] },
  { id:"s-jeonjucheon", rid:"jeonju", region:"전주", title:"전주천 벚꽃길", cat:"대표", desc:"한옥마을 옆 전주천변 산책로. 한복+벚꽃.", photo:"한복+벚꽃+전주천 구도. 한옥 지붕 배경.", atmo:"전통적", crowd:"보통", tr:{sub:"없음",bus:"전주역→시내버스",car:"전주IC 15분",prk:"한옥마을 주차장",day:"KTX 서울 1.5시간"}, tags:["한옥","한복","전통"] },
  { id:"s-namcheon", rid:"busan", region:"부산", title:"남천동 벚꽃길", cat:"숨은", desc:"광안대교 뷰+벚꽃. 부산만의 특별한 봄.", photo:"광안대교+벚꽃 구도. 골든아워 촬영.", atmo:"바다+도시", crowd:"보통", tr:{sub:"2호선 남천역",bus:"남천동 방면",car:"수영IC 10분",prk:"어려움",day:"부산 시내"}, tags:["바다","광안대교","야경"] }
];
